version: '3.9'
services:
  db:
    image: postgres:15
    container_name: banco-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: adonis-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_DATABASE: mydatabase
      NODE_ENV: production
    ports:
      - '3333:3333'
    depends_on:
      - db
    networks:
      - mynetwork
    restart: always

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - '8080:80'
    depends_on:
      - api
    networks:
      - mynetwork
    restart: always

volumes:
  postgres-data:
    name: banco-postgres

networks:
  mynetwork:
